M48
; DRILL file {KiCad 8.0.3} date 2024-06-24T10:15:48-0300
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2024-06-24T10:15:48-03:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.3
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C2.200
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.500
%
G90
G05
T1
X110.5Y-81.0
X142.0Y-116.5
X148.0Y-72.5
T2
X147.93Y-107.5
M30
